services:
  playlist-pilot:
    container_name: playlist-pilot
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    env_file:
      - .env
    environment:
      PYTHONPATH: /app
      TZ: ${TZ:-UTC}
      PYTHONUNBUFFERED: 1
    ports:
      - 8010:8000
    volumes:
      - ${LOGS_DIR:-./logs}:/app/logs
      - ${CACHE_DIR:-./cache}:/app/cache
      - ${USER_DATA_DIR:-./user_data}:/app/user_data
      - ${SETTINGS_PATH:-./settings.json}:/app/settings.json:rw
      - ./data:/data # Ensures /data/.cache-spotify is persisted
      - ${MUSIC_DIR:-/mnt/Movies-And-More/Music}:/Movies/Music
    restart: unless-stopped
    healthcheck:
      test:
        - CMD
        - python3
        - -c
        - import urllib.request;
          urllib.request.urlopen('http://localhost:8000/health')
      interval: 120s
      timeout: 10s
      retries: 3
networks: {}
